//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.19 at 02:58:00 AM JST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:yahoo:jp:chiebukuro", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nawa.mysearch.quest.xjc;
