//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.19 at 02:58:00 AM JST 
//


package com.nawa.mysearch.quest.xjc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Result" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="QuestionId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="QuestionUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CategoryId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CategoryPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsMobile" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="HasImage" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="AnsCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Coin" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="BestAnswer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="UpdatedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="totalResultsAvailable" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="totalResultsReturned" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="firstResultPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "result"
})
@XmlRootElement(name = "ResultSet")
public class ResultSet {

    @XmlElement(name = "Result")
    protected List<ResultSet.Result> result;
    @XmlAttribute(name = "totalResultsAvailable")
    protected BigInteger totalResultsAvailable;
    @XmlAttribute(name = "totalResultsReturned")
    protected BigInteger totalResultsReturned;
    @XmlAttribute(name = "firstResultPosition")
    protected BigInteger firstResultPosition;

    /**
     * Gets the value of the result property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the result property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultSet.Result }
     * 
     * 
     */
    public List<ResultSet.Result> getResult() {
        if (result == null) {
            result = new ArrayList<ResultSet.Result>();
        }
        return this.result;
    }

    /**
     * Gets the value of the totalResultsAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalResultsAvailable() {
        return totalResultsAvailable;
    }

    /**
     * Sets the value of the totalResultsAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalResultsAvailable(BigInteger value) {
        this.totalResultsAvailable = value;
    }

    /**
     * Gets the value of the totalResultsReturned property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalResultsReturned() {
        return totalResultsReturned;
    }

    /**
     * Sets the value of the totalResultsReturned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalResultsReturned(BigInteger value) {
        this.totalResultsReturned = value;
    }

    /**
     * Gets the value of the firstResultPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFirstResultPosition() {
        return firstResultPosition;
    }

    /**
     * Sets the value of the firstResultPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFirstResultPosition(BigInteger value) {
        this.firstResultPosition = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="QuestionId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="QuestionUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CategoryId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CategoryPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IsMobile" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="HasImage" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="AnsCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="Coin" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="BestAnswer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="UpdatedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "questionId",
        "questionUrl",
        "content",
        "categoryId",
        "category",
        "categoryPath",
        "isMobile",
        "hasImage",
        "ansCount",
        "coin",
        "bestAnswer",
        "updatedDate"
    })
    public static class Result {

        @XmlElement(name = "QuestionId", required = true)
        protected BigInteger questionId;
        @XmlElement(name = "QuestionUrl", required = true)
        protected String questionUrl;
        @XmlElement(name = "Content")
        protected String content;
        @XmlElement(name = "CategoryId", required = true)
        protected BigInteger categoryId;
        @XmlElement(name = "Category", required = true)
        protected String category;
        @XmlElement(name = "CategoryPath", required = true)
        protected String categoryPath;
        @XmlElement(name = "IsMobile")
        protected boolean isMobile;
        @XmlElement(name = "HasImage")
        protected boolean hasImage;
        @XmlElement(name = "AnsCount", required = true)
        protected BigInteger ansCount;
        @XmlElement(name = "Coin")
        protected BigInteger coin;
        @XmlElement(name = "BestAnswer")
        protected String bestAnswer;
        @XmlElement(name = "UpdatedDate", required = true)
        protected String updatedDate;

        /**
         * Gets the value of the questionId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getQuestionId() {
            return questionId;
        }

        /**
         * Sets the value of the questionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setQuestionId(BigInteger value) {
            this.questionId = value;
        }

        /**
         * Gets the value of the questionUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQuestionUrl() {
            return questionUrl;
        }

        /**
         * Sets the value of the questionUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQuestionUrl(String value) {
            this.questionUrl = value;
        }

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the categoryId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCategoryId() {
            return categoryId;
        }

        /**
         * Sets the value of the categoryId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCategoryId(BigInteger value) {
            this.categoryId = value;
        }

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategory(String value) {
            this.category = value;
        }

        /**
         * Gets the value of the categoryPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoryPath() {
            return categoryPath;
        }

        /**
         * Sets the value of the categoryPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoryPath(String value) {
            this.categoryPath = value;
        }

        /**
         * Gets the value of the isMobile property.
         * 
         */
        public boolean isIsMobile() {
            return isMobile;
        }

        /**
         * Sets the value of the isMobile property.
         * 
         */
        public void setIsMobile(boolean value) {
            this.isMobile = value;
        }

        /**
         * Gets the value of the hasImage property.
         * 
         */
        public boolean isHasImage() {
            return hasImage;
        }

        /**
         * Sets the value of the hasImage property.
         * 
         */
        public void setHasImage(boolean value) {
            this.hasImage = value;
        }

        /**
         * Gets the value of the ansCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAnsCount() {
            return ansCount;
        }

        /**
         * Sets the value of the ansCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAnsCount(BigInteger value) {
            this.ansCount = value;
        }

        /**
         * Gets the value of the coin property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCoin() {
            return coin;
        }

        /**
         * Sets the value of the coin property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCoin(BigInteger value) {
            this.coin = value;
        }

        /**
         * Gets the value of the bestAnswer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBestAnswer() {
            return bestAnswer;
        }

        /**
         * Sets the value of the bestAnswer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBestAnswer(String value) {
            this.bestAnswer = value;
        }

        /**
         * Gets the value of the updatedDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUpdatedDate() {
            return updatedDate;
        }

        /**
         * Sets the value of the updatedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUpdatedDate(String value) {
            this.updatedDate = value;
        }

    }

}
